-- 1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);


-- 2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);



-- 3.
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

-- 4. 
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5. 
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

-- 6.

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;

-- 7. 
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C0011261 TO PK_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C0011260 TO PK_NO;

ALTER TABLE TB_CATEGORY RENAME CONSTRAINT PK_NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT PK_NO TO PK_CLASS_TYPE_NO;

ALTER TABLE TB_CATEGORY RENAME CONSTRAINT CATEGORY_NAME TO PK_CATEGORY_NAME;

-- 8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9. 
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

GRANT CREATE SESSION TO WORKBOOK;
GRANT CREATE VIEW TO  WORKBOOK;

-- 10.
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름 , STUDENT_ADDRESS 주소 FROM TB_STUDENT;



-- 11.
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME AS 학생이름 , DEPARTMENT_NO AS 학과이름, NVL(COACH_PROFESSOR_NO,'없음') AS 지도교수 FROM TB_STUDENT
ORDER BY DEPARTMENT_NO;

-- 12.
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO) AS STUDENT_COUNT
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;



-- 13.
UPDATE VW_학생일반정보
SET 학생이름 = '장하은'
WHERE 학번 = 'A213046';

-- 14.
-- WITH READ ONLY
-- VIEW 자체를 수정하지 못하게 차단하는 옵션을 추가하면 된다

-- 15. 
SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) "누적수강생수(명)"
FROM (
    SELECT COUNT(*)
    FROM TB_GRADE
    GROUP BY CLASS_NO, TERM_NO
    HAVING TERM_NO LIKE '2007%' OR TERM_NO LIKE '2008%' OR TERM_NO LIKE '2009%'
)

