-- 1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);


-- 2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);



-- 3.
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

-- 4. 
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5. 
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

-- 6.

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;

-- 7. 
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C0011261 TO PK_NAME;  --잘못만듦
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C0011260 TO PK_NO; --잘못만듦

ALTER TABLE TB_CATEGORY RENAME CONSTRAINT PK_NAME TO CATEGORY_NAME; --잘못만듦
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT PK_NO TO PK_CLASS_TYPE_NO;

ALTER TABLE TB_CATEGORY RENAME CONSTRAINT CATEGORY_NAME TO PK_CATEGORY_NAME;

-- 8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9. 
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

GRANT CREATE SESSION TO WORKBOOK;
GRANT CREATE VIEW TO  WORKBOOK;

-- 10.
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름 , STUDENT_ADDRESS 주소 FROM TB_STUDENT;



-- 11.
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME AS 학생이름 , DEPARTMENT_NAME AS 학과이름, NVL(PROFESSOR_NAME,'없음') AS 지도교수
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
ORDER BY DEPARTMENT_NAME;

DROP VIEW VW_지도면담;
SELECT * FROM  VW_지도면담;

-- 12.
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO) AS STUDENT_COUNT
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;



-- 13.
UPDATE VW_학생일반정보
SET 학생이름 = '장하은'
WHERE 학번 = 'A213046';

-- 14.
-- WITH READ ONLY
-- VIEW 자체를 수정하지 못하게 차단하는 옵션을 추가하면 된다

-- 15. 
SELECT S.*
FROM (
    SELECT G.CLASS_NO 과목번호, T.CLASS_NAME 과목이름, COUNT(G.CLASS_NO) "누적수강생수(명)"
    FROM TB_CLASS T
    JOIN TB_GRADE G ON(T.CLASS_NO = G.CLASS_NO)
    WHERE G.TERM_NO >= '200701'
    GROUP BY G.CLASS_NO, T.CLASS_NAME
    ORDER BY "누적수강생수(명)" DESC
   
) S
WHERE ROWNUM <=3;


    