-- 1.
SELECT *
FROM JOB;

-- 2. 
SELECT JOB_NAME
FROM JOB;

-- 3.
SELECT *
FROM DEPARTMENT;

-- 4.
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

-- 5. 
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

-- 6.
SELECT EMP_NAME, SALARY*12 연봉 , (SALARY+ SALARY*NVL(BONUS,0))*12 총수령액, (SALARY + SALARY*NVL(BONUS,0))*12-((SALARY*12)*0.3) 실수령액
FROM EMPLOYEE;

-- 7.
SELECT EMP_NAME 이름, SALARY 월급, HIRE_DATE 고용일, PHONE 연락처
FROM EMPLOYEE
WHERE SAL_LEVEL ='S1';

-- 8.
SELECT EMP_NAME, SALARY, (SALARY + SALARY*NVL(BONUS,0))*12-((SALARY*12)*0.3) AS 실수령액, HIRE_DATE
FROM EMPLOYEE
WHERE (SALARY + SALARY*NVL(BONUS,0))*12-((SALARY*12)*0.3) >= 50000000;

-- 9.
SELECT *
FROM EMPLOYEE
WHERE SALARY >= 4000000 AND JOB_CODE = 'J2';

-- 10.
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5') AND HIRE_DATE < '020101';

-- 11.
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE  BETWEEN '900101' AND '010101';

-- 12.
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '__연';

-- 13.
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE != '010%';

-- 14.
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '____\_%' ESCAPE '\' AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6') AND 
      (HIRE_DATE  BETWEEN'900101' AND '001201') AND SALARY > 2700000;
        
-- 15.
SELECT EMP_NAME, (SUBSTR(EMP_NO,1,2)) AS 생년, (SUBSTR(EMP_NO,3,2)) AS 생월, (SUBSTR(EMP_NO,5,2)) AS 생일
FROM EMPLOYEE;

-- 16.
SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, 7),14,'*')
FROM EMPLOYEE;

-- 17.
SELECT EMP_NAME, 
    FLOOR(ABS(HIRE_DATE - SYSDATE)) AS 근무일수1,
    FLOOR(SYSDATE - HIRE_DATE) AS 근무일수2
FROM EMPLOYEE;

-- 18.
SELECT *
FROM EMPLOYEE
WHERE MOD(EMP_ID, 2) = 1;

-- 19.
SELECT *
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE) >= 20;

-- 20.
SELECT EMP_NAME, TO_CHAR(SALARY, 'L9,999,999') 급여
FROM EMPLOYEE;

-- 21.
SELECT EMP_NAME, NVL(DEPT_CODE, '부서없음') 부서코드, TO_CHAR(TO_DATE(SUBSTR(EMP_NO,1,6)),'YY"년" MM"월" DD"일"') AS 생년월일,
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,2), 'RRRR'))|| '세' AS 나이,
    TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), TO_DATE(SUBSTR(EMP_NO,1,6), 'RRMMDD')) / 12)
    
FROM EMPLOYEE;

-- 22.
SELECT EMP_NAME,DECODE(DEPT_CODE, 'D5', '총무부', 'D6', '기획부', 'D9', '영업부') AS 부서코드
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D6' ,'D9')
ORDER BY 부서코드;

-- 23.
SELECT EMP_NAME, SUBSTR(EMP_NO, 1,6) 사, SUBSTR(EMP_NO, 8,14),
        SUBSTR(EMP_NO, 1,6)+SUBSTR(EMP_NO, 8,14) AS 합
FROM EMPLOYEE
WHERE EMP_ID= '201';

-- 24.
SELECT SUM((SALARY+ SALARY*NVL(BONUS,0))*12) AS "연봉 합"
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5';

-- 25.
SELECT EXTRACT(YEAR FROM HIRE_DATE) 입사년도, COUNT(*) AS "입사 인원수"
FROM EMPLOYEE
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
ORDER BY EXTRACT(YEAR FROM HIRE_DATE);
